### ISSUE TITLE
iptb shell shouldn't complain about IPFS_PATH

### ISSUE THREAD

**Issue by Stebalien** [ipfs/iptb#105]
I set my own IPFS_PATH for my local node. `iptb shell` should just override it, it shouldn't complain about it.

**Comment by travisperson** [comment]
> I set my own IPFS_PATH for my local node. iptb shell should just override it, it shouldn't complain about it.

It complains because it can't guarantee it will override, it which could lead to bad things for the end user. The user could have it set in some configuration file which is loaded when a new shell is launched, which will override anything set by iptb.

If you know a good way to work around this issue that would be awesome.

**Comment by Stebalien** [comment]
Damn, that's annoying.

Closing as I really can't think of a cross-platform (shell) solution (even a hacky one).
